version: '3.4'

services:
  testdb:
    container_name: testdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"

  testdocker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=testdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
    depends_on: 
      - testdb
    ports:
      - "5005:80"

  pgadmin:
    container_name: pgadmin
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
     - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
     - 5050:80
    volumes:
     - pgadmin_data:/root/.pgadmin
